/* This is the info needed to ODBC directly to Redshift (bbprod). */
libname rshift odbc dsn=redshift user=jwillingham password=redacted schema=public;

/* The path on the SAS server used to store permanent SAS data sets. */
libname perm '/mnt/sasdata/Turner/Post_Cereal/';

/* The path on the SAS server used to store the scripts. */
%let code = /home/jwillingham/scripts/Turner/Post_Cereal/;
/* The path on the SAS server used for the Bash code generated by SAS. */
%let path = /mnt/sasdata/Turner/Post_Cereal/;
/* This is the 'target' name, used to differentiate output statistics. */
%let sample = 'HH w/ Children 10-12, All Toon Campaigns';
/* Time period start date used throughout the analysis, in SAS format. */
%let period_start = '05OCT2015'd;
/* Time period end date used throughout the analysis, in SAS format. */
%let period_end = '31JAN2016'd;
/* Self-explanatory, I hope. */
%let live_offset = 3*24*60*60;
/* Self-explanatory, I hope. */
%let mso = (1,3,4);
/* Enter pk_id from demographic_xwalk, used to filter households demographically. Note that a comma-delimited list may be entered, yet the demographic must be mutally exclusive and within category. */
%let target_demos = (204);
/* Self-explanatory, I hope. */
%let intab_src = households_intab_cpg;
/* Self-explanatory, I hope. */
%let all_campaigns = (27782,27783,27785,27786,27787,27788,27789,27790,27792,27793);
/* Self-explanatory, I hope. */
%let target_campaigns = (27782,27783,27785,27786,27787,27788);
/* Generates Bash to connect to bbprodnew on RDS. */
%let rds_bbprod = %str(mysql -h bbprodnew.cftzigz5ukfp.us-east-1.rds.amazonaws.com -P 3306 -u masteruser --password=redacted);
/* Generates Bash to connect to bbops on Redshift. */
%let rshift_bbops = %str(export pgpassword='redacted' && psql -h bbops.chvsirwznppl.us-east-1.redshift.amazonaws.com -p 5439 -d production -U jwillingham);
/* Generates Bash to connect to bbprod on Redshift. */
%let rshift_bbprod = %str(export pgpassword='redacted' && psql -h bbprod.chvsirwznppl.us-east-1.redshift.amazonaws.com -p 5439 -d production -U jwillingham);
/* Adds a timestamp to output files. */
%let stamp = %sysfunc(catx(_,%sysfunc(compress(%sysfunc(today(),yymmddd10.),'-')),%sysfunc(compress(%sysfunc(time(),time.),':'))));

/* Used to tweak the weighting algorithm. As of now the 'backend' code is written for a television-only universe, so leave these as is. */
%let bucket = 100;
%let iterations = 100;
%let projection = 114649000;

/* The code below executes the 'backend' and 'rakinge' code, then calls the macros used to generate the Reach, Frequency and GRP stats. */
%include "&code.rf_report_backend.sas";
%include "&code.rf_report_rakinge.sas";

%households_intab();
%household_weighting();
%viewership_data();
%demographic_targets();

%rf_grp_period();
%reach_wk();
%cum_reach_wk();